typography_spectrum: 0.5435959093738347
color:
  brandStrength: 0.16543671675026417
  lightness: 0.956877555930987
  saturation: 0.2926786008756608
  rhythmicContrast: 0.9874895222019404
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.5783868043217808
name: XtivePro
navigation:
  - name: >-
      'Bike to the Future': Design Museum Gent considers a world of two-wheeled
      design.
    id: 9f50ad8a-ae48-4dc0-8da0-810c5271730d
    type: content
title: Simplicity in Home Excercise
